### PR TITLE
`is.na()` : handle FLAT and CONSTANT

### LINKED ISSUE #89: `r_base::is.na()`: INTERNAL Error: Operation requires a flat vector but a non-flat vector was encountered
With duckdb 0.10.2, which has rfuns embedded:

``` r
duckdb <- asNamespace("duckdb")
drv <- duckdb::duckdb()
con <- DBI::dbConnect(drv)
experimental <- FALSE
invisible(duckdb$rapi_load_rfuns(drv@database_ref))
df1 <- data.frame(a = 1:6)

rel365 <- duckdb$rel_from_df(con, df1, experimental = experimental)
rel366 <- duckdb$rel_project(
  rel365,
  list({
    tmp_expr <- duckdb$expr_constant(NA_real_)
    duckdb$expr_set_alias(tmp_expr, "d")
    tmp_expr
  })
)
rel367 <- duckdb$rel_project(
  rel366,
  list({
    tmp_expr <- duckdb$expr_function("r_base::is.na", list(duckdb$expr_reference("d")))
    duckdb$expr_set_alias(tmp_expr, "e")
    tmp_expr
  })
)
rel367
#> DuckDB Relation: 
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Projection [r_base::is.na(d) as e]
#>   Projection [NULL as d]
#>     r_dataframe_scan(0x10462b0a8)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - e (BOOLEAN)
duckdb$rel_to_altrep(rel367)
#> Error: Error evaluating duckdb query: INTERNAL Error: Operation requires a flat vector but a non-flat vector was encountered
```

<sup>Created on 2024-05-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #89

### CODE REVIEW

File: duckdb-rfuns-r/tests/testthat/test-is_na.R [hunk 1]
```diff
@@ -1,3 +1,45 @@
+test_that("rfuns.is.na() handles CONSTANT input", {
+  withr::local_options(list(duckdb.materialize_message = FALSE))
+  con <- local_duckdb_con()
+
+  duckdb <- asNamespace("duckdb")
+  experimental <- FALSE
+  df1 <- data.frame(a = 42)
+
+  is_na_constant <- function(value) {
+    rel365 <- duckdb$rel_from_df(con, df1, experimental = experimental)
```
Comment (romainfrancois) [inline duckdb-rfuns-r/tests/testthat/test-is_na.R:10]: This could be simpler if `rel_from_df` handled data frames with no columns.

Comment (romainfrancois) [reply duckdb-rfuns-r/tests/testthat/test-is_na.R:10]:
``` r
library(duckdb)
#> Loading required package: DBI
library(tibble)

duckdb <- asNamespace("duckdb")
drv <- duckdb::duckdb()
con <- DBI::dbConnect(drv)

duckdb$rel_from_df(con, tibble(.rows = 1L))
#> Error: rel_from_df: Invalid data frame
```

<sup>Created on 2024-05-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

File: duckdb-rfuns-r/tests/testthat/test-is_na.R [hunk 2]
```diff
@@ -1,3 +1,45 @@
...
+  expect_true(is_na_constant(NA_integer_))
+  expect_true(is_na_constant(NA_character_))
+
+  expect_false(is_na_constant(42))
+  expect_false(is_na_constant(42L))
+  expect_false(is_na_constant(TRUE))
+  expect_false(is_na_constant(FALSE))
+
+  skip("I don't know why it returns NA: will investigate")
+  expect_true(is_na_constant(NA))
```
Comment (romainfrancois) [inline duckdb-rfuns-r/tests/testthat/test-is_na.R:40]: Need to investigate what happens here

Comment (romainfrancois) [reply duckdb-rfuns-r/tests/testthat/test-is_na.R:40]: That's what's happening: https://github.com/duckdb/duckdb-r/pull/161 we get a `SQLNULL` and that perhaps does not go though `isna_any`

Comment (romainfrancois) [reply duckdb-rfuns-r/tests/testthat/test-is_na.R:40]: After some investigation, it appears we don't get to call the function at all when `value` is a `SQLNULL`, even if we add a bind step. 

So I believe we should instead allow creation of a `LOGICAL` NULL constant in https://github.com/duckdb/duckdb-r/pull/161 and keep `skip()` in the meantime

File: src/is_na.cpp [hunk 3]
```diff
@@ -11,82 +11,125 @@ namespace rfuns {
...
+
+			*result_data = ConstantVector::IsNull(input) || isnan(*ldata);
+
+			break;
+		}
+
+		default: {
+			// TODO: use UnifiedVectorFormat instead
+			throw InvalidInputException("is.na() only handles constant and flat vectors");
+			break;
```
Comment (romainfrancois) [inline src/is_na.cpp:68]: Do we need to implment this now ?

File: duckdb-rfuns-r/tests/testthat/test-is_na.R (hunk 1 above)
Comment (krlmlr) [reply duckdb-rfuns-r/tests/testthat/test-is_na.R:10]: Let's keep it as is.

Comment (krlmlr) [reply duckdb-rfuns-r/tests/testthat/test-is_na.R:10]: At least for now.

File: src/is_na.cpp (hunk 3 above)
Comment (krlmlr) [reply src/is_na.cpp:68]: I don't know.

File: duckdb-rfuns-r/tests/testthat/test-is_na.R (hunk 2 above)
Comment (krlmlr) [reply duckdb-rfuns-r/tests/testthat/test-is_na.R:40]: @hannes: How does propagation of `NULL` values work? The `is.na()` function is special in that it needs to return `TRUE` if passed an `SQLNULL`, do we need to define this function in a special way?

We need a function here because `is.na === is.na | is.nan` for doubles and `is.na` for all other types.

File: src/is_na.cpp (hunk 3 above)
Comment (romainfrancois) [reply src/is_na.cpp:68]: I'll have a look to see what's involved. I'm not sure though how to create a vector that is niether flat or constant

**Comment by romainfrancois** [comment]
Added some code for the `!FLAT & ! CONSTANT` case, which turned out to be easy enough after all. I don't know how to test it though. How would I get a vector that is neither FLAT not CONSTANT ?
